### ISSUE TITLE
Playing offline

### ISSUE THREAD

**Issue by seriousgamer42** [tassaron/batchfile.py#1]
Hey, I'm trying to do it so that I can play funtimes offline. Can someone ANYONE, please help me?

**Comment by tassaron** [comment]
What system are you using? If you want to play the original game on Windows, you can do that without Python just by running Funtimes.bat

If you want to play the Python-interpreted version, you need Python 3.6 or higher installed. The newest version is fine. The one built into MacOS is not fine because it's too old.

Then you run funtimes.py using Python from a commandline. For example you would type `python.exe funtimes.py` on Windows or `python3` instead
